// Generated 21 May 2018 10:40 - Singular Systems Object Generator Version 2.2.694
//<auto-generated/>
using System;
using Csla;
using Csla.Serialization;
using Csla.Data;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Singular;
using System.Data;
using System.Data.SqlClient;


namespace MELib.RO
{
	[Serializable]
	public class ROUserList
	 : MEReadOnlyListBase<ROUserList, ROUser>
	{
		#region " Business Methods "

		public ROUser GetItem(int UserID)
		{
			foreach (ROUser child in this)
			{
				if (child.UserID == UserID)
				{
					return child;
				}
			}
			return null;
		}

		public override string ToString()
		{
			return "Users";
		}

		#endregion

		#region " Data Access "

		[Serializable]
		public class Criteria
			: CriteriaBase<Criteria>
		{
			public string ForgotEmail { get; set; }
			public Criteria()
			{
			}

		}

		public static ROUserList NewROUserList()
		{
			return new ROUserList();
		}

		public ROUserList()
		{
			// must have parameter-less constructor
		}

		public static ROUserList GetROUserList()
		{
			return DataPortal.Fetch<ROUserList>(new Criteria());
		}
		public static ROUserList GetROUserListForForgotEmail(string forgotEmail)
		{
			return DataPortal.Fetch<ROUserList>(new Criteria { ForgotEmail = forgotEmail });
		}

		protected void Fetch(SafeDataReader sdr)
		{
			this.RaiseListChangedEvents = false;
			this.IsReadOnly = false;
			while (sdr.Read())
			{
				this.Add(ROUser.GetROUser(sdr));
			}
			this.IsReadOnly = true;
			this.RaiseListChangedEvents = true;
		}

		protected override void DataPortal_Fetch(Object criteria)
		{
			Criteria crit = (Criteria)criteria;
			using (SqlConnection cn = new SqlConnection(Singular.Settings.ConnectionString))
			{
				cn.Open();
				try
				{
					using (SqlCommand cm = cn.CreateCommand())
					{
						cm.CommandType = CommandType.StoredProcedure;
						cm.CommandText = "GetProcs.getROUserList";
						cm.Parameters.AddWithValue("@ForgotEmail", Misc.NothingDBNull(crit.ForgotEmail));
						using (SafeDataReader sdr = new SafeDataReader(cm.ExecuteReader()))
						{
							Fetch(sdr);
						}
					}
				}
				finally
				{
					cn.Close();
				}
			}
		}

		#endregion

	}

}